services:
  - type: web
    name: mrwan-ai-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ZAI_API_KEY
        sync: false
