services:
  - type: web
    name: n8n-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
